server:  
  port: 8090
  session-timeout: 30  
  tomcat.max-threads: 0  
  tomcat.uri-encoding: UTF-8

spring:
  datasource:
    url: jdbc:mysql://82.157.145.14:3306/citycup?useUnicode=true&useSSL=false&serverTimezone=GMT&characterEncoding=UTF-8
    username: root
    password: "%jHUlEuIfUwW^jda7s}L"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    default-property-inclusion: non_null